# Generated by Django 3.0.14 on 2021-12-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20211201_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
