# Generated by Django 3.0.14 on 2022-02-19 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20220219_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='appointment_ID',
            new_name='activity_ID',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='account_ID',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='opportunityName',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='salesmemeber',
        ),
        migrations.AddField(
            model_name='activity',
            name='dateSelected',
            field=models.DateField(blank=True, help_text='Year-Month-Day', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='timeSelected',
            field=models.TimeField(blank=True, help_text='Hour:Minute:Second', null=True),
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('status_history_ID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('activity_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Activity')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status History',
            },
        ),
        migrations.CreateModel(
            name='PresalesMember',
            fields=[
                ('presales_member_ID', models.AutoField(primary_key=True, serialize=False)),
                ('external_presales_member_ID', models.CharField(max_length=50)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.UserRole')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='members',
            field=models.ManyToManyField(to='management.PresalesMember'),
        ),
    ]
