# Generated by Django 3.0.14 on 2022-02-24 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_activity_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presalesmember',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.UserRole'),
        ),
    ]
