# Generated by Django 3.2.12 on 2022-03-08 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20220308_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='createdByMember',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createdByMember', to='management.presalesmember'),
        ),
    ]
