# Generated by Django 3.2.12 on 2022-03-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_activity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='members',
            field=models.ManyToManyField(blank=True, to='management.PresalesMember'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='oneDateTime',
            field=models.DateTimeField(blank=True, help_text='Year-Month-Day Hour:Minute:Second', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='selectedDateTime',
            field=models.DateTimeField(blank=True, help_text='Year-Month-Day Hour:Minute:Second', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='threeDateTime',
            field=models.DateTimeField(blank=True, help_text='Year-Month-Day Hour:Minute:Second', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='twoDateTime',
            field=models.DateTimeField(blank=True, help_text='Year-Month-Day Hour:Minute:Second', null=True),
        ),
    ]
