# Generated by Django 3.2.12 on 2022-03-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_auto_20220313_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activtyType',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='opportunity_ID',
            field=models.CharField(max_length=100),
        ),
    ]
