# Generated by Django 3.2.12 on 2022-03-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_activity_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='test',
        ),
    ]
