# Generated by Django 3.2.12 on 2022-03-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_remove_activity_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('Accept', 'accept'), ('Reschedule', 'reschedule'), ('Request', 'request'), ('Cancel', 'cancel'), ('Decline', 'decline'), ('Expire', 'expire')], default='Request', max_length=50),
        ),
    ]
