# Generated by Django 3.2.12 on 2022-03-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('Accept', 'accept'), ('Reschedule', 'reschedule'), ('Scheduled', 'scheduled'), ('Request', 'request'), ('Cancel', 'cancel'), ('Decline', 'decline'), ('Expire', 'expire')], default='Request', max_length=50),
        ),
        migrations.AlterField(
            model_name='presalesmember',
            name='proficiency',
            field=models.ManyToManyField(blank=True, null=True, to='management.Proficiency'),
        ),
    ]
