# Generated by Django 3.2.12 on 2022-03-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_auto_20220321_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presalesmember',
            name='proficiency',
            field=models.ManyToManyField(blank=True, to='management.Proficiency'),
        ),
    ]
