# Generated by Django 3.2.12 on 2022-03-22 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_alter_presalesmember_proficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('type_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activtyType',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_Level',
            field=models.CharField(choices=[('Level 1', 'Level 1: PowerPoint'), ('Level 2', 'Level 2: Demo'), ('Level 3', 'Level 3: Requirements'), ('Level 4', 'Level 4: Demo/Questions')], default='Level 1', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='activty_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.activitytype'),
        ),
    ]
