# Generated by Django 3.2.12 on 2022-03-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_alter_activity_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(choices=[('Remote', 'remote'), ('Onsite', 'onsite')], default='Remote', max_length=50),
        ),
    ]
