# Generated by Django 3.2.12 on 2022-03-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_alter_activity_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('Accept', 'accept'), ('Reschedule', 'reschedule'), ('Scheduled', 'scheduled'), ('Request', 'request'), ('Cancel', 'cancel'), ('Decline', 'decline'), ('Expire', 'expire'), ('Complete', 'complete')], default='Request', max_length=50),
        ),
    ]
