# Generated by Django 3.2.12 on 2022-03-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_alter_activity_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activty_Type',
            new_name='activity_Type',
        ),
    ]
