# Generated by Django 3.2.12 on 2022-03-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
    ]
