# Generated by Django 3.2.12 on 2022-03-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_remove_activity_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PresalesMember',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='presales_member_ID',
            new_name='member_ID',
        ),
    ]
