# Generated by Django 3.2.12 on 2022-03-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0044_alter_note_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='external_presales_member_ID',
            new_name='external_member_ID',
        ),
    ]
