# Generated by Django 3.2.12 on 2022-03-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0046_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='oneDateTime',
            field=models.DateTimeField(help_text='Year-Month-Day Hour:Minute:Second'),
        ),
    ]
