# Generated by Django 3.2.12 on 2022-04-17 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0057_member_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='info',
            new_name='token',
        ),
    ]
