# Generated by Django 3.2.12 on 2022-04-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0060_remove_member_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_Level',
            field=models.CharField(blank=True, choices=[('Level 1', 'Level 1: PowerPoint'), ('Level 2', 'Level 2: Demo'), ('Level 3', 'Level 3: Requirements'), ('Level 4', 'Level 4: Demo/Questions')], default='Level 1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=models.CharField(max_length=500),
        ),
    ]
