# Generated by Django 3.2.12 on 2022-05-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0061_auto_20220422_2049'),
        ('management', '0061_auto_20220428_2122'),
    ]

    operations = [
    ]
