# Generated by Django 3.0.14 on 2021-12-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20211201_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='time',
            field=models.TimeField(help_text='Hour:Minute:Second'),
        ),
    ]
