# Generated by Django 3.0.14 on 2021-12-01 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20211201_2309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
