# Generated by Django 3.0.14 on 2022-02-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20211201_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('roles_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Activity',
        ),
        migrations.AddField(
            model_name='product',
            name='external_product_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
