# Generated by Django 3.0.14 on 2022-02-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20220219_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='oneDate',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='oneTime',
        ),
        migrations.AddField(
            model_name='activity',
            name='oneDateTime',
            field=models.DateTimeField(blank=True, help_text='Year-Month-Day Hour:Minute:Second', null=True),
        ),
    ]
