# Generated by Django 3.0.14 on 2022-02-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20220219_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
