# Generated by Django 3.2.12 on 2022-03-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_auto_20220310_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('Status_ID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Accept', 'accept'), ('Reschedule', 'reschedule'), ('Request', 'request'), ('Cancel', 'cancel'), ('Decline', 'decline'), ('Expire', 'expire')], default='Request', max_length=50)),
            ],
            options={
                'verbose_name': 'Status Table',
            },
        ),
    ]
