# Generated by Django 3.2.12 on 2022-03-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_auto_20220310_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusHistory',
        ),
    ]
