# Generated by Django 3.2.12 on 2022-03-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_alter_activity_opportunity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activtyType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
