# Generated by Django 3.2.12 on 2022-03-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_auto_20220313_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='test',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
