# Generated by Django 3.2.12 on 2022-03-14 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_alter_activity_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
