# Generated by Django 3.2.12 on 2022-03-24 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_rename_activty_type_activity_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_ID', models.AutoField(primary_key=True, serialize=False)),
                ('note_text', models.CharField(max_length=500)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.userrole')),
            ],
        ),
    ]
