# Generated by Django 3.2.12 on 2022-03-24 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_auto_20220324_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.member'),
        ),
    ]
