# Generated by Django 3.2.12 on 2022-03-25 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0045_rename_external_presales_member_id_member_external_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.activitytype'),
        ),
    ]
