# Generated by Django 3.2.12 on 2022-03-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0049_auto_20220330_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiency',
            name='level',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
