# Generated by Django 3.2.12 on 2022-03-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0050_alter_proficiency_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
