# Generated by Django 3.2.12 on 2022-03-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0051_auto_20220330_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
