# Generated by Django 3.2.12 on 2022-04-07 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0052_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activeManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activeManager', to='management.member'),
        ),
    ]
