# Generated by Django 3.2.12 on 2022-04-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0054_note_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
