# Generated by Django 3.2.12 on 2022-04-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0056_rename_available_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
