# Generated by Django 3.2.12 on 2022-04-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0058_rename_info_member_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
