# Generated by Django 3.2.12 on 2022-04-20 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0059_alter_member_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='token',
        ),
    ]
